Repository konflux-ci/image-controller, pull requests merged in 2023-08, with the labels that each got.

#49 Add type to upload secret
  controllers/component_image_controller.go
  controllers/component_image_controller_test.go
Labels: lgtm, ok-to-test

#51 chore: Adding more log for quay intermittent issue
  pkg/quay/quay.go
Labels: lgtm

#52 Enable hermetic builds in RHTAP
  .tekton/image-controller-pull-request.yaml
  .tekton/image-controller-push.yaml
Labels: lgtm

#54 feat: Added function to check if imageRepo is public
  pkg/quay/quay.go
  pkg/quay/quay_debug_test.go
  pkg/quay/quay_test.go
Labels: lgtm

#55 Add test cases for controller
  controllers/component_image_controller.go
  controllers/component_image_controller_test.go
  controllers/suite_util_test.go
Labels: lgtm

#46 Implement Image Controller API
  Dockerfile
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/imagerepository_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/appstudio.redhat.com_imagerepositories.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_imagerepositories.yaml
  config/crd/patches/webhook_in_imagerepositories.yaml
  config/rbac/imagerepository_editor_role.yaml
  config/rbac/imagerepository_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/appstudio.redhat.com_v1alpha1_controller.yaml
  config/samples/appstudio.redhat.com_v1alpha1_imagerepository.yaml
  config/samples/kustomization.yaml
  controllers/component_image_controller.go
  controllers/component_image_controller_test.go
  controllers/imagerepository_controller.go
  controllers/imagerepository_controller_test.go
  controllers/imagerepository_controller_unit_test.go
  controllers/suite_test.go
  controllers/suite_util_quay_client_test.go
  controllers/suite_util_test.go
  hack/boilerplate.go.txt
  main.go
  pkg/quay/quay.go
  pkg/quay/quay_debug_test.go
  pkg/quay/quay_test.go
Labels: ok-to-test

#58 feat: add "last_modified" to repository metadata
  pkg/quay/api.go
Labels: lgtm

#59 Update README with new API
  README.md
Labels: lgtm
